// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------------ //
// bidir_dshot_x1_new //
// ------------------ //

#define bidir_dshot_x1_new_wrap_target 1
#define bidir_dshot_x1_new_wrap 31

#define bidir_dshot_x1_new_CLKDIV_300_INT 22
#define bidir_dshot_x1_new_CLKDIV_300_FRAC 0
#define bidir_dshot_x1_new_CLKDIV_600_INT 11
#define bidir_dshot_x1_new_CLKDIV_600_FRAC 0
#define bidir_dshot_x1_new_CLKDIV_1200_INT 5
#define bidir_dshot_x1_new_CLKDIV_1200_FRAC 128

static const uint16_t bidir_dshot_x1_new_program_instructions[] = {
	0x8020, //  0: push   block
			//     .wrap_target
	0xe081, //  1: set    pindirs, 1
	0x80a0, //  2: pull   block
	0x6070, //  3: out    null, 16
	0xee00, //  4: set    pins, 0                [14]
	0x6e01, //  5: out    pins, 1                [14]
	0xe801, //  6: set    pins, 1                [8]
	0x00e4, //  7: jmp    !osre, 4
	0xe080, //  8: set    pindirs, 0
	0xe035, //  9: set    x, 21
	0x01ca, // 10: jmp    pin, 10                [1]
	0xe046, // 11: set    y, 6
	0x000f, // 12: jmp    15
	0xe04c, // 13: set    y, 12
	0xa1e1, // 14: mov    osr, x                 [1]
	0x00d5, // 15: jmp    pin, 21
	0x008f, // 16: jmp    y--, 15
	0x4061, // 17: in     null, 1
	0xa027, // 18: mov    x, osr
	0x004d, // 19: jmp    x--, 13
	0x0000, // 20: jmp    0
	0xe146, // 21: set    y, 6                   [1]
	0x0019, // 22: jmp    25
	0xe04c, // 23: set    y, 12
	0xa0e1, // 24: mov    osr, x
	0x00db, // 25: jmp    pin, 27
	0x000b, // 26: jmp    11
	0x0099, // 27: jmp    y--, 25
	0xe021, // 28: set    x, 1
	0x4021, // 29: in     x, 1
	0xa027, // 30: mov    x, osr
	0x0057, // 31: jmp    x--, 23
			//     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program bidir_dshot_x1_new_program = {
	.instructions = bidir_dshot_x1_new_program_instructions,
	.length = 32,
	.origin = -1,
};

static inline pio_sm_config bidir_dshot_x1_new_program_get_default_config(uint offset) {
	pio_sm_config c = pio_get_default_sm_config();
	sm_config_set_wrap(&c, offset + bidir_dshot_x1_new_wrap_target, offset + bidir_dshot_x1_new_wrap);
	return c;
}
#endif
