// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------ //
// extended_spi //
// ------------ //

#define extended_spi_wrap_target 0
#define extended_spi_wrap 1

static const uint16_t extended_spi_program_instructions[] = {
            //     .wrap_target
    0x7501, //  0: out    pins, 1         side 0 [5] 
    0x5c01, //  1: in     pins, 1         side 1 [4] 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program extended_spi_program = {
    .instructions = extended_spi_program_instructions,
    .length = 2,
    .origin = -1,
};

static inline pio_sm_config extended_spi_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + extended_spi_wrap_target, offset + extended_spi_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}

#include "hardware/gpio.h"
static inline void pio_spi_init(PIO pio, uint sm, uint prog_offs, uint n_bits,
								float clkdiv, uint pin_sck, uint pin_mosi, uint pin_miso) {
	pio_sm_config c = extended_spi_program_get_default_config(prog_offs);
	sm_config_set_out_pins(&c, pin_mosi, 1);
	sm_config_set_in_pins(&c, pin_miso);
	sm_config_set_sideset_pins(&c, pin_sck);
	// Only support MSB-first in this example code (shift to left, auto push/pull, threshold=nbits)
	sm_config_set_out_shift(&c, false, true, n_bits);
	sm_config_set_in_shift(&c, false, true, n_bits);
	sm_config_set_clkdiv(&c, clkdiv);
	// MOSI, SCK output are low, MISO is input
	pio_sm_set_pins_with_mask(pio, sm, 0, (1u << pin_sck) | (1u << pin_mosi));
	pio_sm_set_pindirs_with_mask(pio, sm, (1u << pin_sck) | (1u << pin_mosi), (1u << pin_sck) | (1u << pin_mosi) | (1u << pin_miso));
	pio_gpio_init(pio, pin_mosi);
	pio_gpio_init(pio, pin_miso);
	pio_gpio_init(pio, pin_sck);
	// SPI is synchronous, so bypass input synchroniser to reduce input delay.
	hw_set_bits(&pio->input_sync_bypass, 1u << pin_miso);
	pio_sm_init(pio, sm, prog_offs, &c);
	pio_sm_set_enabled(pio, sm, true);
}

#endif
