// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------------- //
// halfduplex_spi_11 //
// ----------------- //

#define halfduplex_spi_11_wrap_target 0
#define halfduplex_spi_11_wrap 5

static const uint16_t halfduplex_spi_11_program_instructions[] = {
	//     .wrap_target
	0x80a0, //  0: pull   block
	0x6081, //  1: out    pindirs, 1
	0x7301, //  2: out    pins, 1         side 0 [3]
	0x5a01, //  3: in     pins, 1         side 1 [2]
	0x00e2, //  4: jmp    !osre, 2
	0x8020, //  5: push   block
	//     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program halfduplex_spi_11_program = {
	.instructions = halfduplex_spi_11_program_instructions,
	.length = 6,
	.origin = -1,
};

static inline pio_sm_config halfduplex_spi_11_program_get_default_config(uint offset) {
	pio_sm_config c = pio_get_default_sm_config();
	sm_config_set_wrap(&c, offset + halfduplex_spi_11_wrap_target, offset + halfduplex_spi_11_wrap);
	sm_config_set_sideset(&c, 2, true, false);
	return c;
}
#endif
