// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// uart_tx //
// ------- //

#define uart_tx_wrap_target 0
#define uart_tx_wrap 0

static const uint16_t uart_tx_program_instructions[] = {
	//     .wrap_target
	0x7f01, //  0: out    pins, 1                [31]
	//     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program uart_tx_program = {
	.instructions = uart_tx_program_instructions,
	.length = 1,
	.origin = -1,
};

static inline pio_sm_config uart_tx_program_get_default_config(uint offset) {
	pio_sm_config c = pio_get_default_sm_config();
	sm_config_set_wrap(&c, offset + uart_tx_wrap_target, offset + uart_tx_wrap);
	return c;
}

#include "hardware/clocks.h"
#include "hardware/gpio.h"
static inline void uart_tx_program_init(PIO pio, uint sm, uint offset, uint pin, uint baud) {
	pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);
	pio_gpio_init(pio, pin);
	pio_sm_config c = uart_tx_program_get_default_config(offset);
	sm_config_set_out_pins(&c, pin, 1);
	// Shift to right, autopull enabled
	sm_config_set_out_shift(&c, true, true, 10);
	// Deeper FIFO as we're not doing any RX
	sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_TX);
	// SM transmits 1 bit per 32 execution cycles.
	float div = (float)clock_get_hz(clk_sys) / (32 * baud);
	sm_config_set_clkdiv(&c, div);
	pio_sm_init(pio, sm, offset, &c);
	pio_sm_set_enabled(pio, sm, true);
}
static inline void uart_tx_program_end(PIO pio, uint sm, uint pin) {
	pio_sm_set_enabled(pio, sm, false);
	pio_sm_clear_fifos(pio, sm);
	pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, false);
	gpio_set_function(pin, GPIO_FUNC_NULL);
}

#endif
