// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------------- //
// onewire_receive //
// --------------- //

#define onewire_receive_wrap_target 3
#define onewire_receive_wrap 9

static const uint16_t onewire_receive_program_instructions[] = {
    0xe001, //  0: set    pins, 1                    
    0xe080, //  1: set    pindirs, 0                 
    0xa0c3, //  2: mov    isr, null                  
            //     .wrap_target
    0xe027, //  3: set    x, 7                       
    0x3720, //  4: wait   0 pin, 0               [23]
    0x4e01, //  5: in     pins, 1                [14]
    0x0045, //  6: jmp    x--, 5                     
    0x00c9, //  7: jmp    pin, 9                     
    0x0202, //  8: jmp    2                      [2] 
    0x8320, //  9: push   block                  [3] 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program onewire_receive_program = {
    .instructions = onewire_receive_program_instructions,
    .length = 10,
    .origin = -1,
};

static inline pio_sm_config onewire_receive_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + onewire_receive_wrap_target, offset + onewire_receive_wrap);
    return c;
}
#endif
