// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------------- //
// onewire_receive //
// --------------- //

#define onewire_receive_wrap_target 2
#define onewire_receive_wrap 7

static const uint16_t onewire_receive_program_instructions[] = {
    0xe001, //  0: set    pins, 1                    
    0xe080, //  1: set    pindirs, 0                 
            //     .wrap_target
    0xe027, //  2: set    x, 7                       
    0x3f20, //  3: wait   0 pin, 0               [31]
    0xaf42, //  4: nop                           [15]
    0x5e01, //  5: in     pins, 1                [30]
    0x0045, //  6: jmp    x--, 5                     
    0x8020, //  7: push   block                      
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program onewire_receive_program = {
    .instructions = onewire_receive_program_instructions,
    .length = 8,
    .origin = -1,
};

static inline pio_sm_config onewire_receive_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + onewire_receive_wrap_target, offset + onewire_receive_wrap);
    return c;
}
#endif
