// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------------- //
// onewire_transmit //
// ---------------- //

#define onewire_transmit_wrap_target 2
#define onewire_transmit_wrap 6

static const uint16_t onewire_transmit_program_instructions[] = {
    0xe001, //  0: set    pins, 1                    
    0xe081, //  1: set    pindirs, 1                 
            //     .wrap_target
    0x80a0, //  2: pull   block                      
    0xff00, //  3: set    pins, 0                [31]
    0x7e01, //  4: out    pins, 1                [30]
    0x00e4, //  5: jmp    !osre, 4                   
    0xfe01, //  6: set    pins, 1                [30]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program onewire_transmit_program = {
    .instructions = onewire_transmit_program_instructions,
    .length = 7,
    .origin = -1,
};

static inline pio_sm_config onewire_transmit_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + onewire_transmit_wrap_target, offset + onewire_transmit_wrap);
    return c;
}
#endif
