// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------------- //
// bidir_dshot_x1 //
// -------------- //

#define bidir_dshot_x1_wrap_target 0
#define bidir_dshot_x1_wrap 22

#define bidir_dshot_x1_CLKDIV_300_INT 22
#define bidir_dshot_x1_CLKDIV_300_FRAC 0
#define bidir_dshot_x1_CLKDIV_600_INT 11
#define bidir_dshot_x1_CLKDIV_600_FRAC 0
#define bidir_dshot_x1_CLKDIV_1200_INT 5
#define bidir_dshot_x1_CLKDIV_1200_FRAC 128

static const uint16_t bidir_dshot_x1_program_instructions[] = {
            //     .wrap_target
    0xa0e3, //  0: mov    osr, null                  
    0x6060, //  1: out    null, 32                   
    0xe081, //  2: set    pindirs, 1                 
    0xe021, //  3: set    x, 1                       
    0xe040, //  4: set    y, 0                       
    0x0005, //  5: jmp    5                          
    0x6070, //  6: out    null, 16                   
    0xee00, //  7: set    pins, 0                [14]
    0x6e01, //  8: out    pins, 1                [14]
    0xe801, //  9: set    pins, 1                [8] 
    0x00e7, // 10: jmp    !osre, 7                   
    0x000f, // 11: jmp    15                         
    0xa022, // 12: mov    x, y                       
    0xe040, // 13: set    y, 0                       
    0x40ff, // 14: in     osr, 31                    
    0xa0c3, // 15: mov    isr, null                  
    0x4001, // 16: in     pins, 1                    
    0xa0e2, // 17: mov    osr, y                     
    0xa046, // 18: mov    y, isr                     
    0x00ac, // 19: jmp    x != y, 12                 
    0xa047, // 20: mov    y, osr                     
    0x0096, // 21: jmp    y--, 22                    
    0x000f, // 22: jmp    15                         
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program bidir_dshot_x1_program = {
    .instructions = bidir_dshot_x1_program_instructions,
    .length = 23,
    .origin = -1,
};

static inline pio_sm_config bidir_dshot_x1_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + bidir_dshot_x1_wrap_target, offset + bidir_dshot_x1_wrap);
    return c;
}
#endif
