// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------- //
// speaker8bit //
// ----------- //

#define speaker8bit_wrap_target 3
#define speaker8bit_wrap 10

static const uint16_t speaker8bit_program_instructions[] = {
    0xa0eb, //  0: mov    osr, !null                 
    0x60c1, //  1: out    isr, 1                     
    0x4068, //  2: in     null, 8                    
            //     .wrap_target
    0x80c0, //  3: pull   ifempty noblock            
    0x6028, //  4: out    x, 8                       
    0xa046, //  5: mov    y, isr                     
    0xe001, //  6: set    pins, 1                    
    0x0088, //  7: jmp    y--, 8                     
    0x0047, //  8: jmp    x--, 7                     
    0xe000, //  9: set    pins, 0                    
    0x018a, // 10: jmp    y--, 10                [1] 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program speaker8bit_program = {
    .instructions = speaker8bit_program_instructions,
    .length = 11,
    .origin = -1,
};

static inline pio_sm_config speaker8bit_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + speaker8bit_wrap_target, offset + speaker8bit_wrap);
    return c;
}
#endif
